# app/database/models.py
"""
ARGUS Database Models
=====================
SQLAlchemy ORM models define database tables as Python classes.

Why models:
- Each class maps directly to a database table
- Each attribute maps to a column
- SQLAlchemy handles all SQL generation
- Type safety — Python knows what type each column is
"""

from sqlalchemy import (
    Column, Integer, String,
    Text, DateTime
)
from sqlalchemy.orm import declarative_base
from datetime import datetime

# Base class that all models inherit from
# SQLAlchemy uses this to track all models
Base = declarative_base()

class Log(Base):
    """
    Represents the logs table.
    Each instance of this class = one row in logs table.
    """
    __tablename__ = "logs"

    id         = Column(Integer, primary_key=True, index=True)
    timestamp  = Column(String,  nullable=False)
    level      = Column(String,  nullable=False, index=True)
    message    = Column(Text,    nullable=False)
    source     = Column(String,  nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert model instance to dictionary for API response"""
        return {
            "id":        self.id,
            "timestamp": self.timestamp,
            "level":     self.level,
            "message":   self.message,
            "source":    self.source
        }

    def __repr__(self):
        return f"<Log id={self.id} level={self.level}>"


class Alert(Base):
    """
    Represents the alerts table.
    Each instance = one security alert generated by rule engine.
    """
    __tablename__ = "alerts"

    id          = Column(Integer, primary_key=True, index=True)
    rule_name   = Column(String,  nullable=False)
    description = Column(Text,    nullable=False)
    severity    = Column(String,  nullable=False, index=True)
    source_ip   = Column(String,  nullable=False)
    log_ids     = Column(Text,    nullable=False)
    status      = Column(String,  default="NEW", index=True)
    created_at  = Column(DateTime, default=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert model instance to dictionary for API response"""
        return {
            "id":          self.id,
            "rule_name":   self.rule_name,
            "description": self.description,
            "severity":    self.severity,
            "source_ip":   self.source_ip,
            "log_ids":     self.log_ids,
            "status":      self.status,
            "created_at":  str(self.created_at)
        }

    def __repr__(self):
        return f"<Alert id={self.id} rule={self.rule_name}>"